approval_policy = "never"
sandbox_mode = "danger-full-access"

[sandbox_workspace_write]
network_access = true

# IMPORTANT: top-level key is `mcp_servers` (not `mcpServers`).

[mcp_servers.serena]
command = "uvx"
args = [
    "--from",
    "git+https://github.com/oraios/serena",
    "serena",
    "start-mcp-server",
    "--context",
    "codex",
]

[tools]
web_search = true

# NOTE: Codex currently supports only stdio-launched MCP servers.
# The `.mcp.json` entry `github` uses HTTP transport and cannot be
# represented directly here. If needed, consider an adapter (e.g., mcp-proxy)
# to wrap an HTTP/SSE MCP endpoint as a local stdio command.
