[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
rmcp = { version = "0.4", features = [
    "server",
    "transport-sse-server",
    "transport-io",
    "transport-streamable-http-server",
] }
tokio = { version = "1", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "io-std",
    "signal",
] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "std",
    "fmt",
] }

# gRPC dependencies
tonic = "0.14"
prost = "0.14"
prost-types = "0.14"
tonic-prost = "0.14"
async-trait = "0.1"
tokio-stream = { version = "0.1" }
uuid = { version = "1.0", features = ["v4"] }

[build-dependencies]
tonic-prost-build = "0.14"

[dev-dependencies]
tokio-util = { version = "0.7", features = ["codec"] }
