[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
async-stream = "0.3.6"
futures = "0.3.31"
prost = "0.14.1"
rmcp = { version = "0.5.0", features = ["server", "transport-io"] }
schemars = "1.0.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1.17", features = ["sync"] }
tonic = { version = "0.14.1", features = ["transport", "tls-webpki-roots"] }
tonic-prost = "0.14.1"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[features]
# Enable gRPC server stubs (needed only for tests here)
server-stubs = []

[dev-dependencies]
tokio-stream = "0.1.17"

[build-dependencies]
tonic-prost-build = "0.14.1"
